"compute cosine",
"compute sine",
"compute tangent",
"compute arc cosine",
"compute arc sine",
"compute arc tangent",
"compute arc tangent with 2 params",
"compute hyperbolic cosine",
"compute hyperbolic sine",
"compute hyperbolic tangent",
"compute area hyperbolic cosine",
"compute area hyperbolic sine",
"compute area hyperbolic tangent",
"compute exponential function",
"compute natural logarithm",
"compute common logarithm",
"compute binary exponential function",
"integer binary logarithm",
"compute binary logarithm",
"raise to power",
"compute square root",
"compute cubic root",
"compute hyptenuse",
"round up value",
"round down value",
"round to nearest",
"round to integral value",
"integer maximum value",
"integer minimum value",
"maximum value",
"minimum value",
"positive difference",
"integer compute absolute value",
"compute absolute value",
"print value of integer",
"print value of float",
"print value of char",
"print value of boolean",
"flush output stream"
