<let_scheme> ::= "let " <ident> (" " <ident>)? "=" <literal> "\n"
<fun_scheme> ::= "fun " <ident> "(" (<parameters> | <whitespace>) ")" (<ident> | <whitespace>) "{" <text>? "}"

<arithmetic_operator> ::= 
    "+" | 
    "-" |
    "*" |
    "/" |
    "%"

<arithmetic_operator_assign> ::= 
    "+=" |
    "-=" |
    "*=" |
    "/=" |
    "%="

<bit_operator> ::= 
    "&"     |
    "|"     |
    "^"     |
    "~"     |
    "<<"    |
    ">>"    |
    "<<<"   |
    ">>>"   |
    "<-"    |
    "->"

<bit_operator_assign> ::= 
    "&="    |
    "|="    |
    "^="    |
    "<<="   |
    ">>="   |
    "<<<="  |
    "=>>>"  |
    "<-="   |
    "->="

<logical_operator> ::=
    "&&" |
    "||" |
    "^^" |
    "!"

<comparison_operator> ::= 
    "=="    |
    "!="    |
    "<"     |
    "<="    |
    ">"     |
    ">="

<operator> ::= 
    <arithmetic_operator>           |
    <arithmetic_operator_assign>    |
    <bit_operator>                  |
    <bit_operator_assign>           |
    <logical_operator>              |
    <comparison_operator>

<comment> ::= "#" <text>

<multi_comment> ::= "##" <text> "##"

<int> ::= ("-" | "+")? <digit> | <int> <digit>

<float> ::= <int> "." <int>

<bool> ::= "true" | "false"

<char> ::= "'" <symbol> "'"

<string> ::= "\"" <text> "\""

<literal> ::= <whitespace>? <literal_content> <whitespace>?

<ident> ::= <whitespace>? <ident_content> <whitespace>?

<ident_content> ::= <letter> | <ident_content> <letter>

<parameter> ::= <ident> " " <ident>

<parameters> ::= <parameter> | <parameters> "," <parameter>

<literal_content> ::= 
    <int>   |
    <float> |
    <bool>  |
    <char>  |
    <string>

<space> ::= 
    " "  |
    "\n" |
    "\t" |
    "\r"

<whitespace> ::= <space> | <whitespace> <space>

<symbol> ::= (<digit> | <letter> | <space>)

<text> ::= (<symbol> | <text> <symbol>)
    
<digit> ::= 
    '0' |
    '1' |
    '2' |
    '3' |
    '4' |
    '5' |
    '6' |
    '7' |
    '8' |
    '9' 

<letter> ::= 
    'A' |
    'B' |
    'C' |
    'D' |
    'E' |
    'F' |
    'G' |
    'H' |
    'I' |
    'J' |
    'K' |
    'L' |
    'M' |
    'N' |
    'O' |
    'P' |
    'Q' |
    'R' |
    'S' |
    'T' |
    'U' |
    'V' |
    'W' |
    'X' |
    'Y' |
    'Z' |
    'a' |
    'b' |
    'c' |
    'd' |
    'e' |
    'f' |
    'g' |
    'h' |
    'i' |
    'j' |
    'k' |
    'l' |
    'm' |
    'n' |
    'o' |
    'p' |
    'q' |
    'r' |
    's' |
    't' |
    'u' |
    'v' |
    'w' |
    'x' |
    'y' |
    'z'
